def count_nuc_DNA(dna_seq):
    #Count Nucleotides number in a string sequence

    counts = {'A':0, 'T':0, 'C':0, 'G':0}

    for nuc in dna_seq:
        if nuc in counts:
            counts[nuc] += 1
    return counts

def count_nuc_DNA2(dna_seq2):   #be careful, only counts, dont look if the file is parsed or ok to read
    #Count Nucleotides number in a string sequence
    return dna_seq2.count("A"), dna_seq2.count("T"), dna_seq2.count("C"), dna_seq2.count("G")

dna = 'TCCGTGTAAACAGAATGACTCATGTCTAGCCCCGTATAAATCGTGGGCTTGTGGAGGATAGCATTCGATCCGATGACAATAGTCAAGCATCTTTAGTTGTCCCCGCGATCCGGACCATATGCAAAGCGGCCCGACCGTGATTTCCTCAGGTTTAAACGATTCAGGGGTATGAAACCGTACTAGCTCAATCTCGCTGTTGTCGCCAGCAGGGGGGTAAATAACCAAAAGTGCAGTCTGAGTTCGACTCGGGACGTCAGAGACCTGTCATAATATCAAAATCATACATTCTTCCACTGTCGCAGCTTTTTATCACAAATTCCGGGCCCGGTCCATCCGGATTGTAAGCGCAATCAATTCCACGAGACATTGGACAGCTCAACGATTAGTGGCATGTATGTTGCAGCGGCAATGGATACACCATAGTAAACCGTTTCGAACGCCCAGTTAGGGATCAACGGAAGCCATCTATGTGCCATTTAATGGGTCCAGCTTCTCTTCATTTGTGGGCCTGTGCACAACTTAATGATCGGGCTGACCAGCCCCCTCACTTGACTCGCCAATCATCAATTATTATCCTGGTTATGAGCAGAATTTCTCCTGGGCGAAGGTACGTCCTCCCTTCACCCTTAATGTCTGCAGGTTGCAAGCGGGTGCGTATTGGCACATTCACTCTGGCGGTTTAATCTGCCCTGGTACCTTCAGATCGCAGTTGAAGGGATTTGCAGCGTCTGTACACGACAGTAGTCATGAGAAAAAGCCCTGGTGGTCGATGACACTCTTTGAGGGAGACCACACGCGCCAGGGTGCTTCCATACGCTATCG'

out = count_nuc_DNA2(dna)

print(out)
